CREATE TABLE IF NOT EXISTS donations(
    id BIGSERIAL PRIMARY KEY,
    donor TEXT NOT NULL,
    amount REAL NOT NULL,
    celebrated BOOLEAN NOT NULL DEFAULT FALSE,
    donated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins(
    id BIGSERIAL PRIMARY KEY,
    discord_id BIGINT NOT NULL
);
